apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
  labels:
    app: sales-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
      - name: sales-api
        image: sales-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: USERS_API_URL
            valueFrom:
              configMapKeyRef:
                name: common-configs
                key: USERS_API_URL
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: common-secrets
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: common-secrets
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: sales-api-secrets
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: common-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-secrets
                key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
