apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouses-api
  labels:
    app: warehouses-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouses-api
  template:
    metadata:
      labels:
        app: warehouses-api
    spec:
      containers:
      - name: warehouses-api
        image: us-central1-docker.pkg.dev/proyecto-final-2-455301/apis-images/warehouses-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: warehouses-api-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_PASSWORD
        - name: USERS_API_URL
          valueFrom:
            configMapKeyRef:
              name: common-configs
              key: USERS_API_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
