apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-api
  labels:
    app: customers-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-api
  template:
    metadata:
      labels:
        app: customers-api
    spec:
      containers:
      - name: customers-api
        image: us-central1-docker.pkg.dev/proyecto-final-2-455301/apis-images/customers-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: customers-api-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_PASSWORD

        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: common-configs
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: common-configs
              key: RABBITMQ_PORT

        - name: USERS_API_URL
          valueFrom:
            configMapKeyRef:
              name: common-configs
              key: USERS_API_URL
        - name: PAYMENT_GATEWAY_URL
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: PAYMENT_GATEWAY_URL

        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
