apiVersion: v1
kind: Service
metadata:
  name: web-bff-service
spec:
  selector:
    app: web-bff
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort
#
#---
#apiVersion: networking.rabbitmq.io/v1
#kind: Ingress
#metadata:
#  name: web-bff-ingress
#  annotations:
#    kubernetes.io/ingress.class: "gce"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: web-bff-service
#            port:
#              number: 80
#
#---
#apiVersion: networking.gke.io/v1
#kind: ManagedCertificate
#metadata:
#  name: bff-cert-v2
#spec:
#  domains:
#    - api.misw4502-ccp.com
#
#---
#apiVersion: networking.rabbitmq.io/v1
#kind: Ingress
#metadata:
#  name: bff-ingress
#  annotations:
#    kubernetes.io/ingress.class: "gce"
#    networking.gke.io/managed-certificates: bff-cert-v2
#    ingress.gcp.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
#    - host: api.misw4502-ccp.com
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: web-bff-service
#                port:
#                  number: 80
