apiVersion: apps/v1
kind: Deployment
metadata:
  name: routes-api
  labels:
    app: routes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routes-api
  template:
    metadata:
      labels:
        app: routes-api
    spec:
      containers:
      - name: routes-api
        image: routes-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: OPENROUTE_API_KEY
          valueFrom:
            secretKeyRef:
              name: routes-api-secrets
              key: OPENROUTE_API_KEY
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: routes-api-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: DB_PASSWORD
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
