name: Sales API CI

on:
  push:
    branches: [ main ]
    paths:
      - 'services/sales/**'
      - '.github/workflows/sales-api-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/sales/**'
      - '.github/workflows/sales-api-ci.yml'

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: sales-service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run tests
      run: |
        pipenv run pytest services/sales/tests/

    - name: Lint
      run: |
        pipenv run pylint services/sales

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./services/sales
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.SERVICE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.SERVICE_NAME }}:${{ github.sha }}