name: CI on main branch

on:
  push:
    branches:
      - 'main'
      - feature/despliege-en-gcp

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  SERVICE_ACCOUNT_FILE: ${{ secrets.SERVICE_ACCOUNT_FILE }}

jobs:
  build-test-apis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run build and Test Script
        run: cd deployment && bash ci_test_apis.sh

  build-test-bffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run build and Test Script
        run: cd deployment && bash ci_test_bffs.sh

  push-to-artifact-registry:
    runs-on: ubuntu-latest
    needs:
      - build-test-apis
      - build-test-bffs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Autenticarse con Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_FILE }}'

      - name: Configurar CLI de gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configurar docker para Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Run build and Push Images
        run: cd deployment && bash build_images.sh --push-all
