name: Deploy to Kubernetes

on:
  workflow_run:
    workflows:
      - "Sales API CI"
      - "Web BFF CI"
    branches: [ main ]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  NAMESPACE: sales-platform

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v2.0

    - name: Configure Kubernetes credentials
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy Sales Service
      run: |
        kubectl set image deployment/sales-service sales-service=${{ env.REGISTRY }}/${{ github.repository }}/sales-service:${{ github.sha }} -n ${{ env.NAMESPACE }}
        kubectl rollout status deployment/sales-service -n ${{ env.NAMESPACE }}

    - name: Deploy Web BFF
      run: |
        kubectl set image deployment/web-bff web-bff=${{ env.REGISTRY }}/${{ github.repository }}/web-bff:${{ github.sha }} -n ${{ env.NAMESPACE }}
        kubectl rollout status deployment/web-bff -n ${{ env.NAMESPACE }}

    - name: Send Deployment Notification
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment successful for Sales Platform
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send Failure Notification
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment failed for Sales Platform
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}